name: flutter_share_example
description: Demonstrates how to use the flutter_share plugin.
version: 0.1.0+1
publish_to: 'none'

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  path_provider: '>=1.4.0'

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_share:
    path: ../


flutter:
  uses-material-design: true
